variables:
  XEN_REGISTRY: registry.gitlab.com/xen-project/xen
  SELECTED_JOBS_ONLY:
    description: "Regex to select only some jobs, must be enclosed with /. For example /job1|job2/"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|smoke|^coverity-tested\/.*|stable-.*)$/
      when: never
    - when: always

stages:
  - analyze
  - build
  - test

include:
  - 'automation/gitlab-ci/analyze.yaml'
  - 'automation/gitlab-ci/build.yaml'
  - 'automation/gitlab-ci/test.yaml'
